version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: effective_mobile
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3308"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  task-management:
    image: task-management:latest
    container_name: task-management
    ports:
    - "8080:8080"
    networks:
      - my_network
volumes:
  db_data:

networks:
  my_network:
    driver: bridge
